// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewIdentity() {
  return window['go']['main']['App']['CreateNewIdentity']();
}

export function DecryptMessage(arg1, arg2) {
  return window['go']['main']['App']['DecryptMessage'](arg1, arg2);
}

export function EncryptMessage(arg1, arg2) {
  return window['go']['main']['App']['EncryptMessage'](arg1, arg2);
}

export function GetAvailableAccounts() {
  return window['go']['main']['App']['GetAvailableAccounts']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetLocalHistory(arg1) {
  return window['go']['main']['App']['GetLocalHistory'](arg1);
}

export function GetMyID() {
  return window['go']['main']['App']['GetMyID']();
}

export function GetMyInfo() {
  return window['go']['main']['App']['GetMyInfo']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function ImportKey(arg1) {
  return window['go']['main']['App']['ImportKey'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SwitchToAccount(arg1) {
  return window['go']['main']['App']['SwitchToAccount'](arg1);
}

export function UpdateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3);
}
